### ISSUE TITLE
[Improvement] Seek Function

### ISSUE THREAD

**Issue by f46b83ee9** [stampzilla/gocast#1]
Hi, I plan on using this awesome library you made, but i thought a seek function would be a nice thing, so here's a draft of how we could make it, I'm not a pro in Go but here's what could be done I think. 

```

func (m *Media) Seek(currentTime int) {
    if m.currentStatus != nil {
        m.Send(&MediaCommand{&MediaSeek{commandMediaSeek, currentTime}, m.currentStatus.MediaSessionID})
    }
}

var commandMediaSeek = responses.Headers{Type: "SEEK"}

type MediaSeek struct {
    responses.Headers
    CurrentTime int `json:"currentTime"`
}

```

I don't know if this code would work but you get the idea, it's a simple JSON sender {Type: "SEEK", CurrentTime: int}.

Hope you can use it :)

**Comment by jonaz** [comment]
If you want you can make a pull request. I can try to implement it when i have the time. Seems easy.

**Comment by f46b83ee9** [comment]
I just did a pull request, thx a lot :)
